# Домашнее задание на проверку знаний библиотеки для анализа данных Pandas.

Вам представлен датасет, который содержит информацию по результатам сезона 2016 года игры в бейсбол.

Вам необходимо загрузить датасет (он находится в архиве с текущим домашним заданием). Провести его очистку, если это необходимо и ответить на поставленные аналитические
вопросы.

Список колонок, представленных в датасете:

---
* attendance        - количество зрителей матча
* away_team         - название гостевой команды
* away_team_errors  - количество ошибок гостевой команды
* away_team_hits    - количество хитов гостевой команды (хит в бейсболе - удар при котором отбивающий достиг первой базы)
* away_team_runs    - количество ранов гостевой команды (ран в бейсболе - очко заработанное игроком нападения)
* date              - дата проведения матча
* field_type        - тип игрового поля
* game_type         - тип игры
* home_team         - название домашней команды
* home_team_errors  - количество ошибок домашней команды
* home_team_hits    - количество хитов домашней команды (хит в бейсболе - удар при котором отбивающий достиг первой базы)
* home_team_runs    - количество ранов домашней команды (ран в бейсболе - очко заработанное игроком нападения)
* start_time        - время начала игрового матча
* venue             - название места проведения матча (стадион, поле, арена)
* day_of_week       - день недели проведения матча
* temperature       - температура воздуха в день проведения матча в фаренгейтах
* wind_speed        - скорость ветра в день проведения матча
* wind_direction    - направление скорости ветра
* sky               - облачность
* total_runs        - общее количество ранов для двух команд
* game_hours_dec    - длительность матча указаная в часах
* season            - тип игрового сезона
* home_team_win     - результат домашней команды (1 - выигрыш)
* home_team_loss    - результат домашней команды (0 - проигрыш)
* home_team_outcome - исход матча
---

Всего в задании 20 вопросов. За каждый правильный вопрос начисляется 5 баллов. Таким образом за все правильные ответы вы получите - 100 баллов. Оценка затем будет приведена к 10-ти бальной шкале.

---

**Баллы могут быть снижены** за качество кода - старайтесь чтобы код был максимально лаконичным. Названия переменных (если они используются) должны отражать максимальную ее сущность. Вывод старайтесь делать минимальным, так как первичная цель - сделать качественный анализ, чтобы быстро ответить на поставленный вопрос (никаких таблиц на 100 строк).

**Требования по сдаче практического задания**:
1. Ответ на вопрос и текстовый markdown с вашей логикой, почему вы выполнили это действие.
2. Залить в репу на github в папку module_1
3. Ссылку на репо отправлять мне на почту alexadevv@gmail.com не позднее дедлайна. 
4. Тема письма: Домашнее задание по модулю 1 <Фамилия Имя>
5. После дедлайна, неотправленные на почту задания, оцениваются максимум в 7 баллов.

In [152]:
# Импортируйте все необходимые библиотеки и модули которые вам необходимы

import numpy as np
import pandas as pd

In [153]:
# Загрузите датасет и проведите его очистку и форматирование если это необходимо
pd.set_option('display.show_dimensions', False)
pd.set_option('display.max_columns', None)

data = pd.read_csv('baseball_games.csv')
data = data.drop('Unnamed: 0', axis=1)

data.isna().sum()
data.describe()
nan_rows = data[data['attendance'].isna()]
#3 значения признака attendance NaN, заполним их медианным значением

median_attendance = data['attendance'].median()
data.fillna({'attendance' : median_attendance}, inplace = True)

# 1. На какую игру пришло максимальное количество зрителей за весь сезон игр?

In [154]:
data[data['attendance'] == data['attendance'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
358,54449.0,Chicago Cubs,0,13,8,2016-10-20,on grass,Night Game,Los Angeles Dodgers,1,9,4,8:09 p.m. Local,Dodger Stadium,Thursday,89.0,7.0,out to Centerfield,Night,12,4.266667,post season,0,1,Loss
360,54449.0,Chicago Cubs,2,13,10,2016-10-19,on grass,Night Game,Los Angeles Dodgers,4,6,2,5:10 p.m. Local,Dodger Stadium,Wednesday,89.0,4.0,out to Rightfield,Night,12,3.966667,post season,0,1,Loss

# 2. Какая игра была самая холодная (temperature) за весь сезон?

In [155]:
data[data['temperature'] == data['temperature'].min()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
2409,32419.0,New York Yankees,1,13,8,2016-04-09,on grass,Day Game,Detroit Tigers,1,7,4,1:10 p.m. Local,Comerica Park,Saturday,31.0,18.0,from Left to Right,Cloudy,12,3.333333,regular season,0,1,Loss

# 3. Какая игра была самая теплая за весь сезон?

In [156]:
data[data['temperature'] == data['temperature'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
2026,21753.0,San Francisco Giants,0,8,3,2016-05-13,on grass,Night Game,Arizona Diamondbacks,0,8,1,6:40 p.m. Local,Chase Field,Friday,101.0,9.0,in unknown direction,Sunny,4,3.0,regular season,0,1,Loss

# 4. Какая игра в сезоне была самая долгая по продолжительности матча?

In [157]:
data[data['game_hours_dec'] == data['game_hours_dec'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
1445,45825.0,Cleveland Indians,0,15,2,2016-07-01,on turf,Day Game,Toronto Blue Jays,2,11,1,1:20 p.m. Local,Rogers Centre,Friday,68.0,0.0,in unknown direction,In Dome,3,6.216667,regular season,0,1,Loss

# 5. Какая игра в сезоне была самая короткая по продолжительности матча?

In [158]:
data[data['game_hours_dec'] == data['game_hours_dec'].min()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
423,19991.0,Chicago Cubs,1,4,1,2016-09-29,on grass,Night Game,Pittsburgh Pirates,0,2,1,7:06 p.m. Local,PNC Park,Thursday,63.0,12.0,in from Leftfield,Overcast,2,1.25,regular season,0,0,Loss

# 6. Сколько матчей в сезоне закончилось ничьей?

In [159]:
data[(data['home_team_win'] == 0) & (data['home_team_loss'] == 0)]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
423,19991.0,Chicago Cubs,1,4,1,2016-09-29,on grass,Night Game,Pittsburgh Pirates,0,2,1,7:06 p.m. Local,PNC Park,Thursday,63.0,12.0,in from Leftfield,Overcast,2,1.25,regular season,0,0,Loss

# 7. Какая игра была последней в сезоне?

In [160]:
data[data['date'] == data['date'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
350,38104.0,Chicago Cubs,3,13,8,2016-11-02,on grass,Night Game,Cleveland Indians,1,11,7,8:02 p.m. Local,Progressive Field,Wednesday,69.0,7.0,from Left to Right,Cloudy,15,4.466667,post season,0,1,Loss

# 8. У какой игры было минимальное количество зрителей?

In [161]:
data[data['attendance'] == data['attendance'].min()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
2130,8766.0,Detroit Tigers,0,5,0,2016-05-04,on grass,Night Game,Cleveland Indians,0,5,4,6:10 p.m. Local,Progressive Field,Wednesday,54.0,11.0,from Left to Right,Overcast,4,2.316667,regular season,1,0,Win

# 9. Какая игра в сезоне была самая ветренная?

In [162]:
data[data['wind_speed'] == data['wind_speed'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
1655,41543.0,Milwaukee Brewers,1,11,5,2016-06-13,on grass,Night Game,San Francisco Giants,0,14,11,7:15 p.m. Local,AT&T Park,Monday,58.0,25.0,out to Centerfield,Cloudy,16,3.633333,regular season,1,0,Win
2005,35736.0,Houston Astros,2,8,9,2016-05-15,on grass,Day Game,Boston Red Sox,3,14,10,1:34 p.m. Local,Fenway Park,Sunday,58.0,25.0,out to Rightfield,Cloudy,19,3.666667,regular season,1,0,Win

# 10. В какой игре получили максимальное количество очков?

In [163]:
data[data['total_runs'] == data['total_runs'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
1788,22588.0,Seattle Mariners,1,16,16,2016-06-02,on grass,Night Game,San Diego Padres,1,20,13,6:10 p.m. Local,Petco Park,Thursday,76.0,10.0,out to Rightfield,Sunny,29,3.833333,regular season,0,1,Loss

# 11. Какая игра содержала максимальное количество ошибок домашней команды?

In [164]:
data[data['home_team_errors'] == data['home_team_errors'].max()]

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,home_team_hits,home_team_runs,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
1178,22581.0,Arizona Diamondbacks,1,11,8,2016-07-27,on grass,Night Game,Milwaukee Brewers,5,5,1,7:10 p.m. Local,Miller Park,Wednesday,77.0,9.0,in from Leftfield,Cloudy,9,2.933333,regular season,0,1,Loss

# 12. В какой игре было максимальное количество хитов?

In [165]:
data['total_hits'] = data['home_team_hits'] + data['away_team_hits']
max_total_hits = data['total_hits'] == data['total_hits'].max()
data[max_total_hits][['attendance', 'away_team_hits', 'home_team_hits', 'total_hits', 'home_team', 'away_team']]

,attendance,away_team_hits,home_team_hits,total_hits,home_team,away_team
1413,36253.0,16,21,37,Boston Red Sox,Texas Rangers

# 13. Выведите количество игр которая сыграла каждая команда в данном сезоне?

In [166]:
away_games = data['away_team'].value_counts()
home_games = data['home_team'].value_counts()
total_games_by_team = home_games.add(away_games, fill_value=0).reset_index()
total_games_by_team.columns = ['team', 'total_games']
total_games_by_team

                             team  total_games
0            Arizona Diamondbacks          162
1                  Atlanta Braves          161
2               Baltimore Orioles          163
3                  Boston Red Sox          165
4                    Chicago Cubs          179
5               Chicago White Sox          162
6                 Cincinnati Reds          162
7               Cleveland Indians          176
8                Colorado Rockies          162
9                  Detroit Tigers          161
10                 Houston Astros          162
11             Kansas City Royals          162
12  Los Angeles Angels of Anaheim          162
13            Los Angeles Dodgers          173
14                  Miami Marlins          161
15              Milwaukee Brewers          162
16                Minnesota Twins          162
17                  New York Mets          163
18               New York Yankees          162
19              Oakland Athletics          162
20          Philadelphia Phillies          162
21             Pittsburgh Pirates          162
22               San Diego Padres          162
23           San Francisco Giants          167
24               Seattle Mariners          162
25            St. Louis Cardinals          162
26                 Tampa Bay Rays          162
27                  Texas Rangers          165
28              Toronto Blue Jays          171
29           Washington Nationals          167

# 14. Какая команда выиграла наибольшое количество матчей в сезоне? (Будьте внимательны с типом матча в сезоне - season).

Сначала посмотрел через **unique** какие сезоны бывают, есть **regular season** и **post season**, видимо имеются в виду только **regular season** игры.

In [167]:
regular_games = data[data['season'] == 'regular season']
home_winners = regular_games[regular_games['home_team_win'] == 1]['home_team']
away_winners = regular_games[regular_games['home_team_loss'] == 1]['away_team']
best_team = pd.concat([home_winners, away_winners]).value_counts()[:1]

print(f'Team "{best_team.index[0]}" won {best_team.values[0]} games')

Team "Chicago Cubs" won 103 games

# 15. Какая команда выиграла наибольшее количество домашних матчей в сезоне?

In [168]:
home_team_won = regular_games['home_team_win'] == 1
best_home_team = regular_games[home_team_won]['home_team'].value_counts()[:1]

print(f'{best_home_team.index[0]} won {best_home_team.values[0]} home games')

Chicago Cubs won 57 home games

# 16. Какая команда выиграла наибольшее количество гостевых матчей в сезоне?

In [169]:
home_team_lost = regular_games['home_team_loss'] == 1
best_away_team = regular_games[home_team_lost]['away_team'].value_counts()[:1]

print(f'{best_away_team.index[0]} won {best_away_team.values[0]} away games')

St. Louis Cardinals won 48 away games

# 17. Какая команда проиграла наибольшее количество матчей в сезоне?

In [170]:
home_losers = regular_games[regular_games['home_team_win'] == 0]['home_team']
away_losers = regular_games[regular_games['home_team_win'] == 1]['away_team']
worst_team = pd.concat([home_losers, away_losers]).value_counts()[:1]

print(f'{worst_team.index[0]} lost {worst_team.values[0]} games')

Minnesota Twins lost 103 games

# 18. Зависит ли выигрыш от количества посетителей матча? (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cov.html)

In [171]:
covariance = data['attendance'].cov(data['home_team_win'])
correlation = data['attendance'].corr(data['home_team_win'])
print(f'Covariance between attendance and win for home team is {covariance}')
print(f'Correlation between attendance and win for home team is {correlation}')

Covariance between attendance and win for home team is 224.73683546545752
Correlation between attendance and win for home team is 0.04561177364260061

Почти не зависит, не знаю является ли такая зависимость значимой.

# 19. Правда ли что большинство проигрышных домашних матчей приходятся на Субботу и Воскресенье?

In [172]:
lost_home_games = data[data['home_team_loss'] == 1]
losses_by_day = lost_home_games['day_of_week'].value_counts(normalize=True)
share_of_Saturday_Sunday = losses_by_day['Saturday'] + losses_by_day['Sunday']

if share_of_Saturday_Sunday > 0.5:
    print(f'Yes, majority ({share_of_Saturday_Sunday:.2%}) of lost home games was played on Saturday and Sunday')
else:
    print(f'No, share of Saturday and Sunday is {share_of_Saturday_Sunday:.2%}')

No, share of Saturday and Sunday is 31.52%

# 20. Правда ли что наибольшее количество ранов происходит в холодную погоду? (Холодной погодой считается погода ниже 0 градусов)

In [173]:
data = pd.read_csv('baseball_games.csv')
data['temperature'] = data.apply(lambda x: round((x['temperature'] - 32 ) / 1.8, 1), axis=1)
number_cold_games = data[data['temperature'] <= 0].index.size
print(f'Total number of games that were played when temperature was 0 or lower: {number_cold_games} of {data.index.size}')

Total number of games that were played when temperature was 0 or lower: 2 of 2463

Только два матча проводились при холодной погоде, выборка мала чтобы сделать такое утверждение. Тем не менее посмотрим при каких температурах игрались матчи с наибольшим количеством ранов

In [174]:
data.sort_values('total_runs', ascending=False).head(10)[['date', 'temperature', 'total_runs', 'home_team', 'away_team']]

,date,temperature,total_runs,home_team,away_team
1788,2016-06-02,24.4,29,San Diego Padres,Seattle Mariners
881,2016-08-22,24.4,27,Cincinnati Reds,Los Angeles Dodgers
2110,2016-05-05,16.7,24,San Francisco Giants,Colorado Rockies
1562,2016-06-21,26.1,24,Minnesota Twins,Philadelphia Phillies
1475,2016-06-28,15.0,24,San Francisco Giants,Oakland Athletics
729,2016-09-04,25.0,24,Minnesota Twins,Chicago White Sox
112,2016-05-25,28.3,24,Texas Rangers,Los Angeles Angels of Anaheim
2052,2016-05-10,29.4,24,Texas Rangers,Chicago White Sox
263,2016-08-19,30.0,23,Baltimore Orioles,Houston Astros
1482,2016-06-28,16.7,23,Colorado Rockies,Toronto Blue Jays

Не видно корреляции между температурой и матчами с наибольшим количеством ранов. Можно также посчитать корреляцию для всей выборки

In [175]:
corr_temp_runs = data['total_runs'].corr(data['temperature'])
print(f'Correlation between total runs and temperature is {corr_temp_runs:.2f}')

Correlation between total runs and temperature is 0.08

В итоге имеется небольшая корреляция в сторону теплой погоды. Погуглив можно вспомнить что более теплая погода уменьшает сопротивление воздуха, поэтому мяч летит немного дальше.